VERSION_NAME=0.1.47
VERSION_CODE=48
LEGACY_GATE_VERSION_NAME=0.1.46
LEGACY_GATE_VERSION_CODE=47
OLDER_GATE_VERSION_NAME=0.1.45
OLDER_GATE_VERSION_CODE=46
OLDEST_GATE_VERSION_NAME=0.1.44
OLDEST_GATE_VERSION_CODE=45
